from _typeshed import Incomplete
from awsglue.utils import callsite as callsite, makeOptions as makeOptions

class StreamingDataSource:
    name: Incomplete
    def __init__(self, j_source, sql_ctx, name) -> None: ...
    def setFormat(self, format, **options) -> None: ...
    def getFrame(self): ...
