from dataclasses import dataclass

__all__ = ['Try', 'Experiment']

@dataclass
class Try:
    number: int
    status: bool | None = ...
    status_message: str | None = ...
    def __init__(self, number, status=..., status_message=...) -> None: ...

@dataclass
class Experiment:
    version: str
    tries: list[Try]
    goal: str | None = ...
    result: str | None = ...
    def __init__(self, version, tries, goal=..., result=...) -> None: ...
