
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-08T14:20:53+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "c6c1d407a9c37e692349ae11318c6ca1cd9e053a",
 "version": "0.6.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
