
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-11T09:38:15+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "97de5e9e7d23f3315746439c301fc7ba00757d7e",
 "version": "0.79"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
