# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class User(UniversalBaseModel):
    user_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    user id
    """

    user_email: typing.Optional[str] = pydantic.Field(default=None)
    """
    user email
    """

    user_phone: typing.Optional[str] = pydantic.Field(default=None)
    """
    user phone
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
