
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-11T15:43:05+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "f4befbfe86448fa686d551b3fc0a507ad2ef6035",
 "version": "1.2.0.post0.dev247"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
