from typing import List, final

__version__: str

@final
class KAdmin:
    def add_principal(self): ...
    def delete_principal(self): ...
    def modify_principal(self): ...
    def rename_principal(self): ...
    def get_principal(self, name: str) -> Principal | None: ...
    def principal_exists(self, name: str) -> bool: ...
    def list_principals(self, query: str) -> List[str]: ...
    def add_policy(self): ...
    def modify_policy(self): ...
    def delete_policy(self): ...
    def get_policy(self): ...
    def list_policies(self, query: str) -> List[str]: ...
    def get_privs(self): ...
    @staticmethod
    def with_local(
        params: Params | None = None, db_args: DbArgs | None = None
    ) -> KAdmin: ...

@final
class Principal:
    def change_password(self, password: str): ...

@final
class Params: ...

@final
class DbArgs: ...
