# coding: utf-8

"""
    Enyday API

    This API allows integration with the Enyday platform, providing access to user authentication, user details, authorization data, address information, and power consumption data. It helps in integrating Enyday into platforms like Home Assistant. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from EnydayPy.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_get_addresses_by_user_id(self) -> None:
        """Test case for get_addresses_by_user_id

        Get Addresses By UserId
        """
        pass

    def test_get_eloverblik_authorizations(self) -> None:
        """Test case for get_eloverblik_authorizations

        Get Eloverblik Authorizations
        """
        pass

    def test_get_hourly_power_data(self) -> None:
        """Test case for get_hourly_power_data

        Get Hourly Power Internal and External By UserId and AddressId
        """
        pass

    def test_get_user_auth_token(self) -> None:
        """Test case for get_user_auth_token

        Get User Auth Token
        """
        pass

    def test_get_user_details(self) -> None:
        """Test case for get_user_details

        Get User Details
        """
        pass


if __name__ == '__main__':
    unittest.main()
