# coding: utf-8

"""
    Enyday API

    This API allows integration with the Enyday platform, providing access to user authentication, user details, authorization data, address information, and power consumption data. It helps in integrating Enyday into platforms like Home Assistant. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from EnydayPy.models.auth_token_response import AuthTokenResponse

class TestAuthTokenResponse(unittest.TestCase):
    """AuthTokenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthTokenResponse:
        """Test AuthTokenResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthTokenResponse`
        """
        model = AuthTokenResponse()
        if include_optional:
            return AuthTokenResponse(
                status = '',
                message = '',
                auth_token = ''
            )
        else:
            return AuthTokenResponse(
        )
        """

    def testAuthTokenResponse(self):
        """Test AuthTokenResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
