
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-10T02:27:00+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2af9926d853086b264680adcf954bf3232f5ec32",
 "version": "1.5.dev2445"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
