"""store receipt url in payment

Revision ID: 21487ff4ab8c
Revises: fda694e67f67
Create Date: 2023-07-08 00:15:49.771279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21487ff4ab8c'
down_revision = 'fda694e67f67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('receipt_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'receipt_url')
    # ### end Alembic commands ###
