"""add date on bills and quotes

Revision ID: ff51555aa2ba
Revises: 7899e98936b3
Create Date: 2023-07-15 08:34:34.201339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff51555aa2ba'
down_revision = '7899e98936b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('bill_date', sa.Date(), nullable=True))
    op.add_column('bill', sa.Column('quote_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bill', 'quote_date')
    op.drop_column('bill', 'bill_date')
    # ### end Alembic commands ###
