# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Notify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

from hs.common.pb.common.constant import NotifyMsgType_pb2 as common_dot_constant_dot_NotifyMsgType__pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Notify.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n2com.huasheng.sa.quant.open.sdk.protobuf.common.msgB\013NotifyProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cNotify.proto\x1a\x19google/protobuf/any.proto\x1a#common/constant/NotifyMsgType.proto\"\x8f\x01\n\x08PBNotify\x12%\n\rnotifyMsgType\x18\x01 \x01(\x0e\x32\x0e.NotifyMsgType\x12\x10\n\x08notifyId\x18\x02 \x01(\t\x12\x12\n\nnotifyTime\x18\x03 \x01(\x04\x12%\n\x07payload\x18\x04 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x0f\n\x07groupId\x18\x05 \x01(\tBA\n2com.huasheng.sa.quant.open.sdk.protobuf.common.msgB\x0bNotifyProtob\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,common_dot_constant_dot_NotifyMsgType__pb2.DESCRIPTOR,])




_PBNOTIFY = _descriptor.Descriptor(
  name='PBNotify',
  full_name='PBNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='notifyMsgType', full_name='PBNotify.notifyMsgType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='notifyId', full_name='PBNotify.notifyId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='notifyTime', full_name='PBNotify.notifyTime', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='PBNotify.payload', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='groupId', full_name='PBNotify.groupId', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=224,
)

_PBNOTIFY.fields_by_name['notifyMsgType'].enum_type = common_dot_constant_dot_NotifyMsgType__pb2._NOTIFYMSGTYPE
_PBNOTIFY.fields_by_name['payload'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['PBNotify'] = _PBNOTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PBNotify = _reflection.GeneratedProtocolMessageType('PBNotify', (_message.Message,), {
  'DESCRIPTOR' : _PBNOTIFY,
  '__module__' : 'Notify_pb2'
  # @@protoc_insertion_point(class_scope:PBNotify)
  })
_sym_db.RegisterMessage(PBNotify)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
