def a1():
	print("""

# -*- coding: utf-8 -*-
IR_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1myOo5xFsdnq79j4j_AdDUfIUnFZl2Rs8


import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer

nltk.download('punkt')
nltk.download('stopwords')

file_path = 'sample.txt'

def preprocess_text_file(file_path):
    # Read the text file
    with open(file_path, 'r', encoding='utf-8') as file:
        text = file.read()

    # Tokenize the text into words
    tokens = word_tokenize(text)

    # Convert to Lowercase
    tokens = [word.lower() for word in tokens]

    # Remove stop words
    stop_words = set(stopwords.words('english'))
    filtered_tokens = [word for word in tokens if word.isalnum() and word not in stop_words]

    # Stemming
    stemmer = PorterStemmer()
    stemmed_tokens = [stemmer.stem(word) for word in filtered_tokens]

    # Join the processed tokens back into a string
    processed_text = ' '.join(stemmed_tokens)

    return processed_text

processed_text = preprocess_text_file(file_path)
print("Processed Text:\n", processed_text)

""")
a1()
