# Generated by Django 5.1.2 on 2024-10-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djreport", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="dotted_path",
            field=models.CharField(
                help_text="E.g. apps.accounting.models.Invoice", max_length=255
            ),
        ),
    ]
