
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-07T17:24:22+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9b55ecded6580199d17302b0f90dd099109a1769",
 "version": "2.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
