giraffe = [ \
'                                                           .                         ..                                 \n',
'                                                        ^?5GGPJ:                  :JPGP5~                               \n',
'                                                       ^5BBB###B!                7B###BBG.                              \n',
'                                                       JB#BBBBB#G.              ~BBBBGGGG:                              \n',
'                                                       ~##BGBBBB#?              ^GGGGGGBP.                              \n',
'                                                        7BBBBGGB#B:             .PBBBB##G:                              \n',
'                                                         ~GGGPPGB#Y             ~GBBGGBBG^                              \n',
'                                                          ~5PGGGGGB5:          ^PBGGGGBBP.                              \n',
'                                                           ?5PGGGGGBG7.      ^JGGGGGGGGGB?                              \n',
'                                    ....                  .7J5GPGGPPGGPJ!^~75PPPPPPGGGGGGG7                 ...::::..   \n',
'                                  .::::::........         ^JJ55JYY5555PGBBBBBGP5Y555P5YPP5Y~     .~7JJ?7!!!7!^^:::::.   \n',
'                                  .^^^^~7JJ5PGGGY!^       !7?J7??JJJJYY5GGGGGGPYJYJJJJJY5PY?    .~~75G#####B57~^:::..   \n',
'                                   ::^~?YB####P?!^^.     :?J5?JYJ?Y5??JYGBBBBBPJ?J?77?JYYGG5.  :~:^~JG#BP5J~^^^^:...    \n',
'                                   .:^~^~!?PBBY7~::^:    75J?Y5??Y??JYY5GGGBBBGGY???7??JJYGP!:~^^:^75B#PJJ7~^:^^:..     \n',
'                                    .:~^~7YB#B57~::^^~^:~YJ75PJ77?YJ?JYPGGGBGGGP55J?77?JYYY5Y!::^:^7PB##G5?~~~^:.       \n',
'                                     .^~^~?G##GJ~:^77777?Y5J7?J?YJYYPP5PPPGBGGGPYYY5YJJJJYYJYJ7~::!YBBBGY77!!^:.        \n',
'                                      .^~~!5###G5J77??JJ!??7!7JYYY5PP5PP55PGGPPP5JY5PP5JYY?7JYJ?Y5G#&#&B5?7!^..         \n',
'                                       .^~~7PBG#&&#Y!?Y?7!7~^~!!?Y5JJ5GP55GGPPP5YY5Y5YJYY7777?JY5BBPGG55J7~:.           \n',
'                                         .:^7JJYPGB?^?PYY7~!^^^~~~7J5YYYPG5P55P5JJPPJ?777?7!7!J??7?JPGY!~.              \n',
'                                            .:~?5J^:~J5555?!^:^::~77?7?PGPYYY5BG?J555?~?!~^!77JY5PPJ7^.                 \n',
'                                                .^:~YGPY?77!^::^!!!^7!?JJJ5GPJPB5?~!7~?J!~^~~7J55P55~                   \n',
'                                                .:^~75B#GJ!^~^^~~~7J~:^!5YGBP??5?7!77??Y5!!^~~!7YPBBY.                  \n',
'                                             .^7?YPGGBBB#BY!~!!~7^JG~^~^!J5Y77PPJ!~!7YY!?!!!~~JGBB57!.                  \n',
'                                          :~J557^^^7#@&#&&#Y~^^::.!57G5^^?PB57YBGJ5!PJ~:::^7!JGB#&#Y?~.                 \n',
'                                      .^7JPGGP5J7!^:5&&&&&G!..:...:~:5P77Y#&#J!7JJG~5J.::::^~P#&&&!   .                 \n',
'                                  :^7JPGBBP55555PGY~PBBBP?^::::~~~...~PPGPGG57~JPPG!~^:7Y7..:!G&#Y                      \n',
'                             .:~7JY5PGBB5?YY555PG5~Y#Y~:..:!77!7!^^..:!5Y!7??77Y##5~..!77^:!!^^7?:                      \n',
'                         .:~7J5PPGPPGGP!!Y5Y55GBY^?B#J!^...:^^:^~^:^^^~5??GBBBPYG#5~~~^:::7?~::.                        \n',
'                      .:~?YPGGGGPPPY?~::J5Y5PGBY:!G##77?^:...:^::..!5GP?75GGGG5JY#PJP77^::~!::.                         \n',
'                    :~?Y5PPGPP555J7^....:J5PGGY:.:557^7Y!77~:^5J:.^5BGJ~?GBPYJ???GG5B5P?^7~::.                          \n',
'                 .^7YPPGGPP55YJJYY5Y?:   :!5P!....:::^??^?YJ~J5J:.!B5!!!!5PPPPPPGY5Y#GY!:!!!^                           \n',
'               .~?5PGGGP55YJ?J5PP555Y!.   .:...:^~:.::??~?557~~:::!PJ5G?!YPPPGGBBPYY#PY5?^~!.                           \n',
'            .^7YPGGGGP5YYJ??YPPP55YYJJ7!:...~?YPGGG5P5G!!5PPY^J7:^!JPGYJ5555PGBBGGGGGPPGY~J^                            \n',
'         .:!J5PGGGP5YYYJ7?Y55PP55YJJJJYP!..:5PPPPGBGGBBYJYP55~YP!^5BPYJY5YY5PGBGBGGGPPP57J?.                            \n',
'       .:!YPGGGGP5YJY?!7Y555PP55YYJJJYJ^....^Y5PGGBGGB#B55GGJ~YGY^5G5J7!7!7?YPBBBBP5?777JY:                             \n',
'     .^!?Y5PGPP55YJ?!7Y5555PPP55YYJY5?. .^^. .^YGGPGG##BG??5?J??J!?PY7!?Y5YJ?J5GBGJJ?Y?7J:                              \n',
'   .:!?JJJY555YYYJ!~J55Y5555555555555^ .?5Y!:  .~7JPGB#BG?.:^!YPPJJYY7!Y5G&#PPG###P5#B5Y!                               \n',
'.:~?JYYYYYYYJJJ?!^:^?JYYYYY555555557: .?5555Y:   ~J5PGBBG5~   .!JYJ???!!JJJPPG##&&#5P5YJ?:                              \n',
'7JY555PP55YJJJ?7~.....~JYYYY55555Y^  .?Y5P555Y:  .:!J55YJ~.     .!~~~!!~7??77JPGBBP???J?J!.                             \n',
'JY5PPP5YJJ??J5555!:.   .:!?Y5555J: .^7Y555PP5Y~      ....      .^~:::^~!77??7!?Y55?!?YY?!~:                             \n',
'PPPPP5YYJJY5PP555Y?^:.    .:!77^. .!JYYYYPPP5Y7               .^^..:::^~~!7?7!7?JJ777?77!~:                             \n',
'GP5YJ??J5PPPP555YYYYYJ!~:.       .?YYJJY5P55YJ: .~!!!^^^:......    .:::^~~!7!!!7?7!!!!~~^^:                             \n',
'5YYJ??YPPPP555555YYYYYYYJ?~:    :?YJYY5555YJ7: .!5YJJJJJJJ~...      .::^^~!!!777J?7!~~^^::.                             \n',
'JJ?7YPPPPP555555555555YYJJJ!.    ...^~!JJ?7^. .?YYYYY5555Y^.         .:^^^~~~!7?J?7~^^:::.                              \n',
'?!^75P5555555YYYY5YYYYYYJJ~.           ....  :JYYYYY555557.             .^^^^~~~~~^^:::.                                \n',
'!...~J55555YYYYY5YYJJJJJ7:   :^:.:.          7YJJJY55PPY^                 .::::::::..                                   \n',
'Y:...^?YYYYYYYYYYJJJYJ!:.   ^JY?7Y7!:...     :7?JJYY55!.                                                                \n',
'5^... ^YYYYYYYJJJJYJ7.   .:~JYYYYYYYJYYJ!.    .^!?JJ!.                                                                  \n',
'5?:.  ^!7???JJJJ77!.    .!JYYYYYYYY5555557. .....:..                                                                    \n',
'55:      ...:^^:.    ..~?YYJJYYYYY55P555YY~  .....                                                                      \n',
'Y~   ..:...        .~?JJJJJJJJYYY555555YJJ?~~^...                                                                       \n',
': .:!?JJJJ?!~^.   .7YYJJJJJJJJYY555P55YYJJJJ?^.                                                                         \n',
'.~?JJJJJYYYYJJ7.  .?YYYYYJJJJJY555555YYYYYY!:.                                                                          \n',
'?JJJJJYYYYYJJ~.   .7JYYJJJJJYYY5Y5P55YYYYY?.                                                                            \n',
'YYYJYYYYYYJJJ.     ..:!JJJJYYY5555555YYYY7.                                                                             \n',
'YYYYYYYYJJY?:         :!~?JYY5P55YYYYY5Y!                                                                               \n',
'YYYY5YJJY?^.  :7^.:.     :7Y555YYYY555Y^                                                                                \n',
'~?YYYYJ?~.  .!JJJJJ?~:.   .~JJJJYYY5J7.                                                                                 \n',
' .^?JJ~.   ^?JJJJJJJJJ!..  ....^J??~:                                                                                   \n',
'^. .:.   .!JJJJJJJJJJYY?7^......:::.                                                                                    \n',
'J?.    .^7YYJYYYJYYYY5555Y7.......                                                                                      \n',
'Y?.    :?YJJJYYYYYY5555YYJJJ~:...                                                                                       \n',
'7:.   :7JJJYYJY55Y55555YYYJ7:::                                                                                         \n',
'.     :7JJYYYYY555PPP5Y5Y?^:^.                                                                                          \n',
' ..    .!JYYYY555PP555YY?^:^.                                                                                           \n',
'~77.     :!Y5555P555YYY7:::                                                                                             \n',
'YYY~      .~~?Y5Y5YYY5Y~:.                                                                                              \n',
'JJY7!~. ......:::~7YY7~^.                                                                                               \n',
'JJJJ??:.:....    ..^^::                                                                                                 \n',
'YYJJ??7JYJ!!:.......:.                                                                                                  \n',
'YYYJJJYY5555J?!.::::.                                                                                                   \n',
'5YYYYY5555YYYYJJ7^:.                                                                                                    \n',
'YYYYY555555YYYYJ::.                                                                                                     \n',
'YY5555PP555555Y~:.                                                                                                      \n',
'Y555PP555P5555?:                                                                                                        \n']