"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chatcompletionchoice import ChatCompletionChoice, ChatCompletionChoiceTypedDict
from .usage import Usage, UsageTypedDict
from friendli.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ChatCompletionResponseTypedDict(TypedDict):
    choices: List[ChatCompletionChoiceTypedDict]
    usage: UsageTypedDict
    created: NotRequired[int]
    r"""The Unix timestamp (in seconds) for when the generation completed."""


class ChatCompletionResponse(BaseModel):
    choices: List[ChatCompletionChoice]

    usage: Usage

    created: Optional[int] = None
    r"""The Unix timestamp (in seconds) for when the generation completed."""
