"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chatcompletionresponse import (
    ChatCompletionResponse,
    ChatCompletionResponseTypedDict,
)
from .streamedtoolassistedchatcompletionresponse import (
    StreamedToolAssistedChatCompletionResponse,
    StreamedToolAssistedChatCompletionResponseTypedDict,
)
from .toolassistedcompletionrequestbody import (
    ToolAssistedCompletionRequestBody,
    ToolAssistedCompletionRequestBodyTypedDict,
)
from friendli.types import BaseModel
from friendli.utils import FieldMetadata, HeaderMetadata, RequestMetadata
import pydantic
from typing import AsyncGenerator, Generator, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict

TOOL_ASSISTED_CHAT_COMPLETION_OP_SERVERS = [
    "https://inference.friendli.ai",
    r"""Friendli Serverless Endpoints.""",
]


class ToolAssistedChatCompletionRequestTypedDict(TypedDict):
    x_friendli_team: NotRequired[str]
    r"""ID of team to run requests as (optional parameter)."""
    tool_assisted_completion_request_body: NotRequired[
        ToolAssistedCompletionRequestBodyTypedDict
    ]


class ToolAssistedChatCompletionRequest(BaseModel):
    x_friendli_team: Annotated[
        Optional[str],
        pydantic.Field(alias="X-Friendli-Team"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""ID of team to run requests as (optional parameter)."""

    tool_assisted_completion_request_body: Annotated[
        Optional[ToolAssistedCompletionRequestBody],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None


ToolAssistedChatCompletionResponseTypedDict = Union[
    ChatCompletionResponseTypedDict,
    Union[
        Generator[StreamedToolAssistedChatCompletionResponseTypedDict, None, None],
        AsyncGenerator[StreamedToolAssistedChatCompletionResponseTypedDict, None],
    ],
]


ToolAssistedChatCompletionResponse = Union[
    ChatCompletionResponse,
    Union[
        Generator[StreamedToolAssistedChatCompletionResponse, None, None],
        AsyncGenerator[StreamedToolAssistedChatCompletionResponse, None],
    ],
]
