# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UnLockTradeRequest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='UnLockTradeRequest.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n5com.huasheng.sa.quant.open.sdk.protobuf.trade.requestB\027UnLockTradeRequestProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18UnLockTradeRequest.proto\"6\n\x12UnLockTradeRequest\x12\x10\n\x08password\x18\x01 \x01(\t\x12\x0e\n\x06unlock\x18\x02 \x01(\tBP\n5com.huasheng.sa.quant.open.sdk.protobuf.trade.requestB\x17UnLockTradeRequestProtob\x06proto3'
)




_UNLOCKTRADEREQUEST = _descriptor.Descriptor(
  name='UnLockTradeRequest',
  full_name='UnLockTradeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='password', full_name='UnLockTradeRequest.password', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unlock', full_name='UnLockTradeRequest.unlock', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['UnLockTradeRequest'] = _UNLOCKTRADEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UnLockTradeRequest = _reflection.GeneratedProtocolMessageType('UnLockTradeRequest', (_message.Message,), {
  'DESCRIPTOR' : _UNLOCKTRADEREQUEST,
  '__module__' : 'UnLockTradeRequest_pb2'
  # @@protoc_insertion_point(class_scope:UnLockTradeRequest)
  })
_sym_db.RegisterMessage(UnLockTradeRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
