from models.stock.financials.balance_sheet_statement.base import BaseBalanceSheetStatementModel

class AnnualBalanceSheetStatementModel(BaseBalanceSheetStatementModel):
    __tablename__ = "stock_financials_annual_balance_sheet_statements"