# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CancelOrderResponse.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CancelOrderResponse.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n6com.huasheng.sa.quant.open.sdk.protobuf.trade.responseB\030CancelOrderResponseProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19\x43\x61ncelOrderResponse.proto\"&\n\x13\x43\x61ncelOrderResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x42R\n6com.huasheng.sa.quant.open.sdk.protobuf.trade.responseB\x18\x43\x61ncelOrderResponseProtob\x06proto3'
)




_CANCELORDERRESPONSE = _descriptor.Descriptor(
  name='CancelOrderResponse',
  full_name='CancelOrderResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='CancelOrderResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=67,
)

DESCRIPTOR.message_types_by_name['CancelOrderResponse'] = _CANCELORDERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CancelOrderResponse = _reflection.GeneratedProtocolMessageType('CancelOrderResponse', (_message.Message,), {
  'DESCRIPTOR' : _CANCELORDERRESPONSE,
  '__module__' : 'CancelOrderResponse_pb2'
  # @@protoc_insertion_point(class_scope:CancelOrderResponse)
  })
_sym_db.RegisterMessage(CancelOrderResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
