
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-11T11:35:57+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "e129bbe8c9a1220a6a4e681498e01f7a3e67c5bf",
 "version": "0.8.0.post0.dev16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
