
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-08T11:08:22+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "17570092caf729244ade9c6d647cfa1d2b9ef5f0",
 "version": "1.2.0.post0.dev109"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
