from backtesting._util import _Data
import pandas_ta as ta




if __name__ == "__main__":
    import datetime
    from backtesting_data.history import historySymbol
    tmp = historySymbol('binanceusdm', 'ETH/USDT', '5m', 100, datetime.datetime(2024, 11, 6, 3))
    data = _Data(tmp)
    data_indicator = stdevIndicator(data, 20)
    print(data_indicator)
    print(data_indicator.get_stdev())
    print(data_indicator.get_stdev().tail(10))
    print(data_indicator.get_stdev().head(10))
    print(data_indicator.get_stdev().shape)
    print(data_indicator.get_stdev().columns)
    print(data_indicator.get_stdev().info())
    print(data_indicator.get_stdev().describe())
    print(data_indicator.get_stdev().tail(10))
    print(data_indicator.get_stdev().head(10))
    print(data_indicator.get_stdev().shape)
    print(data_indicator.get_stdev().columns)
    print(data_indicator.get_stdev().info())
    print(data_indicator.get_stdev().describe())
    print(data_indicator.get_stdev().tail(10))
    print(data_indicator.get_stdev().head(10))
    print(data_indicator.get_stdev().shape)
    print(data_indicator.get_stdev().columns)
    print(data_indicator.get_stdev().info())
    print(data_indicator.get_stdev().describe())
    print(data_indicator.get_stdev().tail(10))
    print(data_indicator.get_stdev().head(10))
    print(data_indicator.get_stdev().shape)
    print(data_indicator.get_stdev().columns)
    print(data_indicator.get_stdev().info())
    print(data_indicator.get_stdev().describe())
    print(data_indicator.get_stdev().tail(10))
    print(data_indicator.get_stdev().head(10))
    print(data_indicator.get_stdev().shape)
    print(data_indicator.get_stdev().columns)
    print(data_indicator.get_stdev().info())
    print(data_indicator.get_stdev().describe())
    print(data_indicator.get_stdev().tail(10))
    print(data_indicator.get_stdev().head(10))
    print(data_indicator.get_stdev().shape)
    print(data_indicator.get_stdev().columns)
    print(data_indicator.get_stdev().info())
    print(data_indicator.get_stdev().describe())
    print(data_indicator.get_stdev().tail(10))
    print(data_indicator.get_stdev().head(10))
    print(data_indicator.get_stdev().shape)
    print(data_indicator.get_stdev().columns)
    print(data_indicator.get_stdev().info())
    print(data_indicator.get_stdev().describe())
    print(data_indicator.get_stdev().tail(10))
    print(data_indicator.get_stdev().head(10))
    print(data_indicator.get_stdev().shape)
    print(data_indicator.get_stdev().columns)
    print(data_indicator.get_stdev().info())
    print(data_indicator.get_stdev().describe())
    print(data_indicator.get_stdev().tail(10))
    print(data_indicator.get_stdev().head(10))
    print(data_indicator.get_stdev().shape)
    print(data_indicator.get_stdev().columns)
    print(data_indicator.get_stdev().info())
    print(data_indicator.get_stdev().describe())
    print(data_indicator.get_stdev().tail(10))
    print(data_indicator.get_stdev().head(10))
    print(data_indicator.get_stdev().shape)
    print(data_indicator.get_stdev().columns)
    print(data_indicator.get_stdev().info())
    print(data_indicator.get_stdev().describe())
    print(data_indicator.get_stdev().tail(10))
    print(data_indicator.get_stdev().head(10))
    print(data_indicator.get_stdev().shape)
    print(data_indicator.get_stdev().columns)
    print(data_indicator.get_stdev().info())
    print(data_indicator.get_stdev().describe())
    print(data_indicator.get_stdev().tail(10))
    print(data_indicator.get_stdev().head(10))
    print(data_indicator.get_stdev().shape)
    print(data_indicator.get_stdev().columns)
    print(data_indicator.get_stdev().info())
    print(data_indicator.get_stdev().describe())
    print(data_indicator.get_stdev().tail(10))
    print(data_indicator.get_stdev().head(10))
    print(data_indicator.get_stdev().shape)
    print(data_indicator.get_stdev().columns)
    print(data_indicator.get_stdev().info())
    print(data_indicator.get_stdev().describe())
    print(data_indicator.get_stdev().tail(10))
    print(data_indicator.get_stdev().head(10))
    print(data_indicator.get_stdev().shape)
    print(data_indicator.get_stdev().columns)
    print(data_indicator.get_stdev().info())
    print(data_indicator.get_stdev().describe())
    print(data_indicator.get_stdev().tail(10))
    print(data_indicator.get_stdev().head(10))
    print(data_indicator.get_stdev().shape)
    print(data_indicator.get_stdev().columns)
    print(data_indicator.get_stdev().info())
    print(data_indicator.get_stdev().describe())
    print(data_indicator.get_stdev().tail(10))
    print(data_indicator.get_stdev().head(