
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-11T14:11:48+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "231aec2928a511ab48f0c9628b93646ef51c3c8f",
 "version": "1.2.0.post0.dev294"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
