
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-09T19:27:08-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ec38b9cf76a2c70635292001f1f885a65f9233fc",
 "version": "0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
