from _typeshed import Incomplete

class ExecutionProperty:
    maxConcurrentRuns: Incomplete
    def __init__(self, maxConcurrentRuns: int = 1) -> None: ...
    def as_dict(self): ...

class Command:
    name: Incomplete
    scriptLocation: Incomplete
    def __init__(self, name, scriptLocation) -> None: ...
    def as_dict(self): ...

class Connections:
    connections: Incomplete
    def __init__(self, connections=[]) -> None: ...
    def as_dict(self): ...

class Job:
    name: str
    description: str
    logUri: str
    role: str
    executionProperty: Incomplete
    command: Incomplete
    defaultArguments: Incomplete
    connections: Incomplete
    maxRetries: int
    allocatedCapacity: int
    createdOn: Incomplete
    lastModifiedOn: Incomplete
    def __init__(self) -> None: ...
    def as_dict(self): ...
    def as_job_create_dict(self): ...
    def as_job_update_dict(self): ...

class GlueJobUtils:
    s3: Incomplete
    glue: Incomplete
    def __init__(self, glue_context) -> None: ...
    def get_jobs(self, nextToken: str = ''): ...
    def get_job(self, jobName): ...
    def create_job(self, job, file: str = ''): ...
    def update_job(self, job, file: str = ''): ...
    def delete_job(self, jobName): ...
