# This file was auto-generated by Fern from our API Definition.

import typing

ActionType = typing.Union[
    typing.Literal["openUrl", "call", "trigger", "requestLocation", "scheduleEvent", "sendLocation"], typing.Any
]
