"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from friendli.types import BaseModel
from typing_extensions import TypedDict


class OtherBuiltInToolType(str, Enum):
    r"""The type of the built-in tool."""

    MATH_CALCULATOR = "math:calculator"
    MATH_STATISTICS = "math:statistics"
    MATH_CALENDAR = "math:calendar"
    WEB_SEARCH = "web:search"
    WEB_URL = "web:url"
    CODE_PYTHON_INTERPRETER = "code:python-interpreter"


class OtherBuiltInToolTypedDict(TypedDict):
    type: OtherBuiltInToolType
    r"""The type of the built-in tool."""


class OtherBuiltInTool(BaseModel):
    type: OtherBuiltInToolType
    r"""The type of the built-in tool."""
