from _typeshed import Incomplete

class DataFrameWriter:
    def __init__(self, glue_context) -> None: ...
    def from_catalog(self, frame, database: Incomplete | None = None, table_name: Incomplete | None = None, redshift_tmp_dir: str = '', transformation_ctx: str = '', additional_options={}, catalog_id: Incomplete | None = None, **kwargs): ...
