import argparse
from typing import Dict

from awsglue.job import Job as Job

def makeOptions(sc, py_obj): ...
def callsite(): ...
def iteritems(d, **kwargs): ...
def iterkeys(d, **kwargs): ...
def itervalues(d, **kwargs): ...

class GlueArgumentError(Exception): ...

class GlueArgumentParser(argparse.ArgumentParser):
    def error(self, msg: str) -> None: ...

def getResolvedOptions(args: list[str], options: list[str]) -> Dict[str, str]: ...
