
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-08T16:53:04+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c2d5d7656d60cd0c5f8cf5a02a683029a586bb22",
 "version": "0.7.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
