
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-10T17:30:39+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f88ac3836dc26e632a892ab1869fda78be1eff5c",
 "version": "0.4.184"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
