
#
# ===== Note =====
#
# This library was auto-generated by AG Remap's APIMirrorBuilder tool,
#   a build system tool used in AG Remap's CI pipeline that creates a mirror for the existing
#   API source code since we cannot rename the original name of 'FixRaidenBoss2' to 'Anime Game Remap' in Pypi,
#   therefore, we decided to make a brand new package that mirrors the original API.
#
# ***** APIMirrorBuilder Stats *****
#
# Version: 1.0.0
# Authors: Albert Gold#2696
# Datetime Ran: Sunday, November 10, 2024 08:34:47.325 AM UTC
# Run Hash: 1068a23e-282b-4c50-9018-970c7cb0d81c
# 
# *******************************
# ================
#

# ===== Anime Game Remap (AG Remap) =====
# Authors: NK#1321, Albert Gold#2696
#
# if you used it to remap your mods pls give credit for "Nhok0169" and "Albert Gold#2696"
# Special Thanks:
#   nguen#2011 (for support)
#   SilentNightSound#7430 (for internal knowdege so wrote the blendCorrection code)
#   HazrateGolabi#1364 (for being awesome, and improving the code)

#
# ***** AG Remap Stats *****
#
# Version: 4.0.1
# Authors: NK#1321, Albert Gold#2696
# Datetime Compiled: Sunday, November 10, 2024 08:34:47.325 AM UTC
# Build Hash: 34c6f91e-31e4-4a2e-ad7f-87865c223c57
#
# ****************************************
#

from FixRaidenBoss2 import remapMain

if __name__ == '__main__':
    remapMain()