from awsglue.transforms import GlueTransform as GlueTransform

class Filter(GlueTransform):
    def __call__(self, frame, f, transformation_ctx: str = '', info: str = '', stageThreshold: int = 0, totalThreshold: int = 0): ...
    @classmethod
    def describeArgs(cls): ...
    @classmethod
    def describeTransform(cls): ...
    @classmethod
    def describeErrors(cls): ...
    @classmethod
    def describeReturn(cls): ...
