# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UsOptionChainCodeResponse.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='UsOptionChainCodeResponse.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n3com.huasheng.sa.quant.open.sdk.protobuf.hq.responseB\036UsOptionChainCodeResponseProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1fUsOptionChainCodeResponse.proto\"/\n\x19UsOptionChainCodeResponse\x12\x12\n\noptionCode\x18\x01 \x03(\tBU\n3com.huasheng.sa.quant.open.sdk.protobuf.hq.responseB\x1eUsOptionChainCodeResponseProtob\x06proto3'
)




_USOPTIONCHAINCODERESPONSE = _descriptor.Descriptor(
  name='UsOptionChainCodeResponse',
  full_name='UsOptionChainCodeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='optionCode', full_name='UsOptionChainCodeResponse.optionCode', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['UsOptionChainCodeResponse'] = _USOPTIONCHAINCODERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UsOptionChainCodeResponse = _reflection.GeneratedProtocolMessageType('UsOptionChainCodeResponse', (_message.Message,), {
  'DESCRIPTOR' : _USOPTIONCHAINCODERESPONSE,
  '__module__' : 'UsOptionChainCodeResponse_pb2'
  # @@protoc_insertion_point(class_scope:UsOptionChainCodeResponse)
  })
_sym_db.RegisterMessage(UsOptionChainCodeResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
