from _typeshed import Incomplete
from awsglue.dynamicframe import DynamicFrame as DynamicFrame
from awsglue.utils import callsite as callsite, makeOptions as makeOptions

class DataSource:
    name: Incomplete
    def __init__(self, j_source, sql_ctx, name) -> None: ...
    def setFormat(self, format, **options) -> None: ...
    def getFrame(self, **options): ...
    def getSampleFrame(self, num, **options): ...
