from _typeshed import Incomplete

class DataFrameReader:
    def __init__(self, glue_context) -> None: ...
    def from_catalog(self, database: Incomplete | None = None, table_name: Incomplete | None = None, redshift_tmp_dir: str = '', transformation_ctx: str = '', push_down_predicate: str = '', additional_options={}, catalog_id: Incomplete | None = None, **kwargs): ...
    def from_options(self, connection_type, connection_options={}, format: Incomplete | None = None, format_options={}, transformation_ctx: str = '', push_down_predicate: str = '', **kwargs): ...
