def a2():
    print('''

# -*- coding: utf-8 -*-
"""Pract_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13A9Yw1umUL8J8LfBER3gkLGiVZ_3cnan
"""

import numpy as np
 import pandas as pd
 from pgmpy.models import BayesianNetwork
 from pgmpy.estimators import MaximumLikelihoodEstimator
 from pgmpy.inference import VariableElimination
 import matplotlib.pyplot as plt
 import networkx as nx

# Step 1: Read Cleveland Heart Disease data
heartDisease = pd.read_csv('heart.csv')
heartDisease = heartDisease.replace('?', np.nan)

heartDisease

# Step 2: Bin the cholesterol levels
bins = [0, 200, 240, 300] # 0-200: Low, 200-240: Medium, 240-300: High
labels = ['Low', 'Medium', 'High']
heartDisease['chol_bin'] = pd.cut(heartDisease['chol'], bins=bins, labels=labels)

# Step 3: Define the Bayesian Network structure
model = BayesianNetwork([
    ('age', 'trestbps'),
    ('age', 'fbs'),
    ('sex', 'trestbps'),
    ('exang', 'trestbps'),
    ('trestbps', 'target'),
    ('fbs', 'target'),
    ('target', 'restecg'),
    ('target', 'thalach'),
    ('target', 'chol_bin')
])

# Step 4: Learn CPDs using Maximum Likelihood Estimators
model.fit(heartDisease, estimator=MaximumLikelihoodEstimator)

# Step 5: Visualize the Bayesian Network using NetworkX with enhanced clarity
plt.figure(figsize=(12, 10))
G = nx.DiGraph()

# Add nodes and edges from the model
for node in model.nodes():
    G.add_node(node)
for edge in model.edges():
    G.add_edge(edge[0], edge[1])

# Define position layout and visual settings for clarity
pos = nx.spring_layout(G, seed=42)  # Consistent layout
nx.draw(G, pos, with_labels=True, arrows=True,
        node_color='skyblue', node_size=3000,
        edge_color='gray', font_size=12, font_weight='bold',
        arrowsize=20, arrowstyle='-|>')

# Step 6: Inferencing with the Bayesian Network
heartDisease_infer = VariableElimination(model)

# Query 1: Probability of Heart Disease given Age 35
q1 = heartDisease_infer.query(variables=['target'], evidence={'age': 35})
print('\n1. Probability of Heart Disease given Age 35:\n', q1)

# Query 2: Probability of Heart Disease given High Cholesterol
q2 = heartDisease_infer.query(variables=['target'], evidence={'chol_bin': 'High'})
print('\n2. Probability of Heart Disease given High Cholesterol:\n', q2)


''')
a2()
