# coding: utf-8

"""
    Teyvatology API Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from teyvatapi.api.o_auth_api import OAuthApi


class TestOAuthApi(unittest.TestCase):
    """OAuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OAuthApi()

    def tearDown(self) -> None:
        pass

    def test_exchange_user_info(self) -> None:
        """Test case for exchange_user_info

        Exchange the one-time token for the avatar link and the JWT token
        """
        pass

    def test_get_google_auth_link(self) -> None:
        """Test case for get_google_auth_link

        Get the google login url
        """
        pass

    def test_google_login_callback(self) -> None:
        """Test case for google_login_callback

        The Google login callback view
        """
        pass


if __name__ == '__main__':
    unittest.main()
