from _typeshed import Incomplete
from awsglue.transforms import GlueTransform as GlueTransform

class Relationalize(GlueTransform):
    def __call__(self, frame, staging_path: Incomplete | None = None, name: str = 'roottable', options: Incomplete | None = None, transformation_ctx: str = '', info: str = '', stageThreshold: int = 0, totalThreshold: int = 0): ...
    @classmethod
    def describeArgs(cls): ...
    @classmethod
    def describeTransform(cls): ...
    @classmethod
    def describeErrors(cls): ...
    @classmethod
    def describeReturn(cls): ...
