from _typeshed import Incomplete
from awsglue.transforms import GlueTransform as GlueTransform

class ResolveChoice(GlueTransform):
    def __call__(self, frame, specs: Incomplete | None = None, choice: str = '', database: Incomplete | None = None, table_name: Incomplete | None = None, transformation_ctx: str = '', info: str = '', stageThreshold: int = 0, totalThreshold: int = 0, catalog_id: Incomplete | None = None): ...
    @classmethod
    def describeArgs(cls): ...
    @classmethod
    def describeTransform(cls): ...
    @classmethod
    def describeErrors(cls): ...
    @classmethod
    def describeReturn(cls): ...
