class PyKAdminException(Exception): ...
class KAdminException(PyKAdminException): ...
class KerberosException(PyKAdminException): ...
class NullPointerDereference(PyKAdminException): ...
class CStringConversion(PyKAdminException): ...
class CStringImportFromVec(PyKAdminException): ...
class StringConversion(PyKAdminException): ...
