
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-07T16:55:36+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "85ab86bf1c0967e45fbec995534cd5a0c9a9c439",
 "version": "0.16.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
