"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from exfunc.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class LinkedInJobPostingTypedDict(TypedDict):
    url: NotRequired[str]
    r"""URL to the job posting"""
    title: NotRequired[str]
    r"""Title of the job"""
    location: NotRequired[str]
    r"""Job location"""
    description: NotRequired[str]
    r"""Detailed description of the job"""
    job_type: NotRequired[str]
    r"""Type of job (e.g., full-time, part-time)"""
    job_function: NotRequired[str]
    r"""Job function or category"""
    industries: NotRequired[str]
    r"""List of industries relevant to the job"""
    seniority_level: NotRequired[str]
    r"""Seniority level of the job (e.g., junior, senior)"""
    applicants: NotRequired[str]
    r"""Number of applicants for the job"""
    date_posted: NotRequired[datetime]
    r"""Date when the job was posted"""
    job_poster_name: NotRequired[str]
    r"""Name of the person who posted the job"""
    job_poster_url: NotRequired[str]
    r"""URL to the job poster's profile"""
    company_name: NotRequired[str]
    r"""Name of the company offering the job"""
    company_url: NotRequired[str]
    r"""URL to the company's profile"""


class LinkedInJobPosting(BaseModel):
    url: Optional[str] = None
    r"""URL to the job posting"""

    title: Optional[str] = None
    r"""Title of the job"""

    location: Optional[str] = None
    r"""Job location"""

    description: Optional[str] = None
    r"""Detailed description of the job"""

    job_type: Optional[str] = None
    r"""Type of job (e.g., full-time, part-time)"""

    job_function: Optional[str] = None
    r"""Job function or category"""

    industries: Optional[str] = None
    r"""List of industries relevant to the job"""

    seniority_level: Optional[str] = None
    r"""Seniority level of the job (e.g., junior, senior)"""

    applicants: Optional[str] = None
    r"""Number of applicants for the job"""

    date_posted: Optional[datetime] = None
    r"""Date when the job was posted"""

    job_poster_name: Optional[str] = None
    r"""Name of the person who posted the job"""

    job_poster_url: Optional[str] = None
    r"""URL to the job poster's profile"""

    company_name: Optional[str] = None
    r"""Name of the company offering the job"""

    company_url: Optional[str] = None
    r"""URL to the company's profile"""
