
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: aio.api.bazel:package

from setuptools import setup

setup(**{
    'author': 'Ryan Northey',
    'author_email': 'ryan@synca.io',
    'description': 'Async wrapper around bazel',
    'entry_points': {
        'console_scripts': [
            'aio.bazel.worker=aio.api.bazel:worker_cmd',
        ],
    },
    'install_requires': (
        'abstracts>=0.0.12',
        'aio.core>=0.10.5',
        'aio.run.runner>=0.3.4',
    ),
    'license': 'Apache Software License 2.0',
    'long_description': """
aio.api.bazel
=============

Async wrapper around bazel
""",
    'maintainer': 'Ryan Northey',
    'maintainer_email': 'ryan@synca.io',
    'name': 'aio.api.bazel',
    'namespace_packages': (
    ),
    'package_data': {
        'aio.api.bazel': (
            'py.typed',
        ),
    },
    'packages': (
        'aio.api.bazel',
        'aio.api.bazel.abstract',
    ),
    'python_requires': '>=3.11.0',
    'url': 'https://bazel.com/envoyproxy/toolshed/tree/main/aio.api.bazel',
    'version': '0.0.3',
})
