# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Request.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

from hs.common.pb.common.constant import RequestMsgType_pb2 as common_dot_constant_dot_RequestMsgType__pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2



DESCRIPTOR = _descriptor.FileDescriptor(
  name='Request.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n2com.huasheng.sa.quant.open.sdk.protobuf.common.msgB\014RequestProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rRequest.proto\x1a\x19google/protobuf/any.proto\x1a$common/constant/RequestMsgType.proto\"\x9e\x01\n\tPBRequest\x12\'\n\x0erequestMsgType\x18\x01 \x01(\x0e\x32\x0f.RequestMsgType\x12\x11\n\trequestId\x18\x02 \x01(\t\x12\x13\n\x0brequestTime\x18\x03 \x01(\x03\x12%\n\x07payload\x18\x04 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x0b\n\x03sid\x18\x05 \x01(\t\x12\x0c\n\x04sign\x18\x06 \x01(\tBB\n2com.huasheng.sa.quant.open.sdk.protobuf.common.msgB\x0cRequestProtob\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,common_dot_constant_dot_RequestMsgType__pb2.DESCRIPTOR,])




_PBREQUEST = _descriptor.Descriptor(
  name='PBRequest',
  full_name='PBRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestMsgType', full_name='PBRequest.requestMsgType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='requestId', full_name='PBRequest.requestId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='requestTime', full_name='PBRequest.requestTime', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='PBRequest.payload', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sid', full_name='PBRequest.sid', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sign', full_name='PBRequest.sign', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=241,
)

_PBREQUEST.fields_by_name['requestMsgType'].enum_type = common_dot_constant_dot_RequestMsgType__pb2._REQUESTMSGTYPE
_PBREQUEST.fields_by_name['payload'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['PBRequest'] = _PBREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PBRequest = _reflection.GeneratedProtocolMessageType('PBRequest', (_message.Message,), {
  'DESCRIPTOR' : _PBREQUEST,
  '__module__' : 'Request_pb2'
  # @@protoc_insertion_point(class_scope:PBRequest)
  })
_sym_db.RegisterMessage(PBRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
