# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ModifyOrderRequest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ModifyOrderRequest.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n5com.huasheng.sa.quant.open.sdk.protobuf.trade.requestB\027ModifyOrderRequestProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18ModifyOrderRequest.proto\"\xc0\x01\n\x12ModifyOrderRequest\x12\x12\n\nmarketType\x18\x01 \x01(\t\x12\x11\n\tportfolio\x18\x02 \x01(\t\x12\x11\n\tstockCode\x18\x03 \x01(\t\x12\x12\n\norderPrice\x18\x04 \x01(\t\x12\x10\n\x08orderQty\x18\x05 \x01(\t\x12\x10\n\x08validity\x18\x06 \x01(\t\x12\x12\n\nexpiryDate\x18\x07 \x01(\t\x12\x13\n\x0b\x64isplaySize\x18\x08 \x01(\t\x12\x0f\n\x07orderId\x18\t \x01(\tBP\n5com.huasheng.sa.quant.open.sdk.protobuf.trade.requestB\x17ModifyOrderRequestProtob\x06proto3'
)




_MODIFYORDERREQUEST = _descriptor.Descriptor(
  name='ModifyOrderRequest',
  full_name='ModifyOrderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='marketType', full_name='ModifyOrderRequest.marketType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='portfolio', full_name='ModifyOrderRequest.portfolio', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stockCode', full_name='ModifyOrderRequest.stockCode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orderPrice', full_name='ModifyOrderRequest.orderPrice', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orderQty', full_name='ModifyOrderRequest.orderQty', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='validity', full_name='ModifyOrderRequest.validity', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expiryDate', full_name='ModifyOrderRequest.expiryDate', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='displaySize', full_name='ModifyOrderRequest.displaySize', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orderId', full_name='ModifyOrderRequest.orderId', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=221,
)

DESCRIPTOR.message_types_by_name['ModifyOrderRequest'] = _MODIFYORDERREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModifyOrderRequest = _reflection.GeneratedProtocolMessageType('ModifyOrderRequest', (_message.Message,), {
  'DESCRIPTOR' : _MODIFYORDERREQUEST,
  '__module__' : 'ModifyOrderRequest_pb2'
  # @@protoc_insertion_point(class_scope:ModifyOrderRequest)
  })
_sym_db.RegisterMessage(ModifyOrderRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
