# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QueryHistoryOrderListRequest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='QueryHistoryOrderListRequest.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n5com.huasheng.sa.quant.open.sdk.protobuf.trade.requestB!QueryHistoryOrderListRequestProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"QueryHistoryOrderListRequest.proto\"\xba\x01\n\x1cQueryHistoryOrderListRequest\x12\x12\n\nmarketType\x18\x01 \x01(\t\x12\x11\n\tportfolio\x18\x02 \x01(\t\x12\x11\n\tstartDate\x18\x03 \x01(\t\x12\x0f\n\x07\x65ndDate\x18\x04 \x01(\t\x12\x14\n\x0cpageQueryKey\x18\x05 \x01(\t\x12\r\n\x05limit\x18\x06 \x01(\t\x12\x17\n\x0forderStatusList\x18\x07 \x03(\t\x12\x11\n\tstockCode\x18\x08 \x01(\tBZ\n5com.huasheng.sa.quant.open.sdk.protobuf.trade.requestB!QueryHistoryOrderListRequestProtob\x06proto3'
)




_QUERYHISTORYORDERLISTREQUEST = _descriptor.Descriptor(
  name='QueryHistoryOrderListRequest',
  full_name='QueryHistoryOrderListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='marketType', full_name='QueryHistoryOrderListRequest.marketType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='portfolio', full_name='QueryHistoryOrderListRequest.portfolio', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='startDate', full_name='QueryHistoryOrderListRequest.startDate', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='endDate', full_name='QueryHistoryOrderListRequest.endDate', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pageQueryKey', full_name='QueryHistoryOrderListRequest.pageQueryKey', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='limit', full_name='QueryHistoryOrderListRequest.limit', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orderStatusList', full_name='QueryHistoryOrderListRequest.orderStatusList', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stockCode', full_name='QueryHistoryOrderListRequest.stockCode', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=225,
)

DESCRIPTOR.message_types_by_name['QueryHistoryOrderListRequest'] = _QUERYHISTORYORDERLISTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueryHistoryOrderListRequest = _reflection.GeneratedProtocolMessageType('QueryHistoryOrderListRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUERYHISTORYORDERLISTREQUEST,
  '__module__' : 'QueryHistoryOrderListRequest_pb2'
  # @@protoc_insertion_point(class_scope:QueryHistoryOrderListRequest)
  })
_sym_db.RegisterMessage(QueryHistoryOrderListRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
