# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade/request/QueryOrderDetailRequest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trade/request/QueryOrderDetailRequest.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n5com.huasheng.sa.quant.open.sdk.protobuf.trade.requestB\034QueryOrderDetailRequestProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n+trade/request/QueryOrderDetailRequest.proto\">\n\x17QueryOrderDetailRequest\x12\x12\n\nmarketType\x18\x01 \x01(\t\x12\x0f\n\x07orderId\x18\x02 \x01(\tBU\n5com.huasheng.sa.quant.open.sdk.protobuf.trade.requestB\x1cQueryOrderDetailRequestProtob\x06proto3'
)




_QUERYORDERDETAILREQUEST = _descriptor.Descriptor(
  name='QueryOrderDetailRequest',
  full_name='QueryOrderDetailRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='marketType', full_name='QueryOrderDetailRequest.marketType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orderId', full_name='QueryOrderDetailRequest.orderId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=109,
)

DESCRIPTOR.message_types_by_name['QueryOrderDetailRequest'] = _QUERYORDERDETAILREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueryOrderDetailRequest = _reflection.GeneratedProtocolMessageType('QueryOrderDetailRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUERYORDERDETAILREQUEST,
  '__module__' : 'trade.request.QueryOrderDetailRequest_pb2'
  # @@protoc_insertion_point(class_scope:QueryOrderDetailRequest)
  })
_sym_db.RegisterMessage(QueryOrderDetailRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
