from .seiRJ import loginSEI,buscarNumeroDocumento,incluirEmBlocoDeAssinatura,incluirDocumentoExterno, escreverAcompanhamentoEspecial,pesquisarProcesso, baixarArquivos, procurarArquivos,obterProcessosDeBloco,buscarProcessoEmBloco,limparAnotacao, escreverAnotacao,buscarInformacaoEmDocumento, incluirDocumento,inserirHyperlinkSEI, incluirProcessoEmBloco,removerProcessoDoBloco,buscarInformacaoEmDocumento
from .siafeRIO import loginSIAFE
from .excel import salvarPlanilha

