"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .streamedchatcompletionchoice import (
    StreamedChatCompletionChoice,
    StreamedChatCompletionChoiceTypedDict,
)
from friendli.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class StreamedToolAssistedChatCompletionResponseDataTypedDict(TypedDict):
    choices: List[StreamedChatCompletionChoiceTypedDict]
    created: int
    r"""The Unix timestamp (in seconds) for when the token sampled."""


class StreamedToolAssistedChatCompletionResponseData(BaseModel):
    choices: List[StreamedChatCompletionChoice]

    created: int
    r"""The Unix timestamp (in seconds) for when the token sampled."""


class StreamedToolAssistedChatCompletionResponseTypedDict(TypedDict):
    r"""A server-sent event containing chat completion content."""

    data: StreamedToolAssistedChatCompletionResponseDataTypedDict


class StreamedToolAssistedChatCompletionResponse(BaseModel):
    r"""A server-sent event containing chat completion content."""

    data: StreamedToolAssistedChatCompletionResponseData
