"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .filebuiltintool import FileBuiltInTool, FileBuiltInToolTypedDict
from .functiontool import FunctionTool, FunctionToolTypedDict
from .otherbuiltintool import OtherBuiltInTool, OtherBuiltInToolTypedDict
from friendli.utils import get_discriminator
from pydantic import Discriminator, Tag
from typing import Union
from typing_extensions import Annotated


ToolForToolAssistedChatTypedDict = Union[
    OtherBuiltInToolTypedDict, FunctionToolTypedDict, FileBuiltInToolTypedDict
]


ToolForToolAssistedChat = Annotated[
    Union[
        Annotated[FunctionTool, Tag("function")],
        Annotated[FileBuiltInTool, Tag("file:text")],
        Annotated[OtherBuiltInTool, Tag("math:calculator")],
    ],
    Discriminator(lambda m: get_discriminator(m, "type", "type")),
]
