
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-07T11:56:33+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "64e8f43c495c207a001c858d524d6b9e8b9892b1",
 "version": "1.30.0.post0.dev121"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
