
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-08T16:50:24+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f80a3e8e4a83c84f40e40f33d90516f126c93de8",
 "version": "1.2.0-rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
