import string
from typing import Any, Mapping, Sequence

from pyspark.pandas.frame import DataFrame
from pyspark.sql import SparkSession

__all__ = ['sql']

def sql(query: str, index_col: str | list[str] | None = None, args: dict[str, Any] | list | None = None, **kwargs: Any) -> DataFrame: ...

class PandasSQLStringFormatter(string.Formatter):
    def __init__(self, session: SparkSession) -> None: ...
    def vformat(self, format_string: str, args: Sequence[Any], kwargs: Mapping[str, Any]) -> str: ...
    def get_field(self, field_name: str, args: Sequence[Any], kwargs: Mapping[str, Any]) -> Any: ...
    def clear(self) -> None: ...
