def b5():
    print("""# -*- coding: utf-8 -*-
'DMV-5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P0K7-0BjjTZhwR9jeJdLFkaUqlWdIwcy
'

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

'# Import the "City_Air_Quality.csv" dataset.'

df = pd.read_csv("City_Air_Quality.csv")
df

'# Explore the dataset to understand its structure and content'

df.shape

df.columns

df.dtypes

df.info()

'# Identify the relevant variables for visualizing AQI trends, such as date, pollutant levels, and AQI values.'

df['Date'] = pd.to_datetime(df['Date'])

'# Create line plots or time series plots to visualize the overall AQI trend over time.'

plt.figure(figsize=(10, 5))
plt.plot(df['Date'], df['AQI'], label='AQI', color='blue')
plt.xlabel('Date')
plt.ylabel('Air Quality Index (AQI)')
plt.title('Air Quality Index Trend Over Time')
plt.legend()
plt.show()

' # Plot individual pollutant levels (e.g., PM2.5, PM10, CO) on separate line plots to visualize their trends over time.'

plt.figure(figsize=(10, 5))
plt.plot(df['Date'], df['PM2.5'], label='AQI', color='purple')
plt.xlabel('Date')
plt.ylabel('PM2.5')
plt.title('PM2.5 Trend Over Time')
plt.legend()
plt.show()

plt.figure(figsize=(10, 5))
plt.plot(df['Date'], df['PM10'], label='AQI', color='orange')
plt.xlabel('Date')
plt.ylabel('PM10')
plt.title('PM10 Trend Over Time')
plt.legend()
plt.show()

plt.figure(figsize=(10, 5))
plt.plot(df['Date'], df['CO'], label='AQI', color='green')
plt.xlabel('Date')
plt.ylabel('CO')
plt.title('CO Trend Over Time')
plt.legend()
plt.show()

'# Use bar plots or stacked bar plots to compare the AQI values across different dates or time periods.'

df['YearMonth'] = df['Date'].dt.to_period('M')
monthly_data = df.groupby('YearMonth').agg({'PM2.5': 'mean', 'PM10': 'mean', 'CO': 'mean'})


monthly_data.plot(kind='bar', figsize=(12, 6))
plt.title('Average AQI by Month')
plt.xlabel('Month')
plt.ylabel('Average AQI Level')
plt.show()

'# Create box plots or violin plots to analyze the distribution of AQI values for different pollutant categories'

plt.figure(figsize=(12,6))
sns.boxplot(data = df[['PM2.5', 'PM10', 'CO']])
plt.ylabel('Concentration')
plt.show()

'# Use scatter plots or bubble charts to explore the relationship between AQI values and pollutant levels.'

plt.figure(figsize=(10, 5))
plt.scatter(df['PM2.5'], df['AQI'], label='PM2.5', alpha=0.5, color='red')
plt.scatter(df['PM10'], df['AQI'], label='PM10', alpha=0.5, color='green')
plt.scatter(df['CO'], df['AQI'], label='CO', alpha=0.5, color='blue')
plt.xlabel('Pollutant Level')
plt.ylabel('Air Quality Index (AQI)')
plt.title('Relationship between AQI and Pollutant Levels')
plt.legend()
plt.grid(True)
plt.show()

""")
b5()

