
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-11T12:25:36+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "928178aaa7e0699ea1b2f5c8125eba344f8533ee",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
